from pathlib import Path
p=Path('js/app.js')
s=p.read_text()

old = '''document.addEventListener('visibilitychange', function() {\n    if (!document.hidden && navigator.onLine && currentFriendPk && currentSystemState === STATE_CONNECTING) {\n        recoverAfterNetworkChange('foreground');\n    }\n});'''
new = '''let appHiddenAt = 0;\nlet foregroundRecoveryTimer = null;\n\nfunction peerConnectionLooksHealthy(peer) {\n    if (!peer || peer.destroyed || !peer.connected) return false;\n    const pc = getPeerConnection(peer);\n    if (!pc) return !!peer.connected;\n    const ice = pc.iceConnectionState;\n    const state = pc.connectionState;\n    return (ice === 'connected' || ice === 'completed') &&\n        (!state || state === 'connected');\n}\n\nfunction restartStaleBackgroundConnections() {\n    for (const [friendPk, session] of backgroundSessions) {\n        if (currentFriendPk === friendPk && currentSystemState !== STATE_READY) continue;\n        if (peerConnectionLooksHealthy(session.peer)) continue;\n        destroyBackgroundPeer(session);\n        session.attempt = 0;\n        startBackgroundSession(friendPk, 'foreground-resume');\n    }\n}\n\nasync function recoverAfterForeground() {\n    if (!navigator.onLine) return;\n    const hiddenForMs = appHiddenAt ? Date.now() - appHiddenAt : 0;\n    logger.debug(`📱 App 回到前景；背景約 ${Math.round(hiddenForMs / 100) / 10}s。`);\n\n    try {\n        await nostr.refreshRelays();\n        isNostrReady = nostr.hasLiveRelay();\n    } catch (_) {\n        isNostrReady = false;\n    }\n\n    if (!isNostrReady) {\n        logger.debug('🟠 回到前景後暫無 Nostr relay，等待 health monitor 恢復。');\n        return;\n    }\n\n    restartStaleBackgroundConnections();\n    startAllBackgroundConnections();\n\n    if (!currentFriendPk || currentSystemState === STATE_READY ||\n        currentSystemState === STATE_CREATE_QR || currentSystemState === STATE_SCAN_QR) return;\n\n    // iOS 可能在背景凍結連線但沒有及時觸發 close/error。\n    // 回到前景時直接檢查底層 ICE/PC，而不是只相信 SimplePeer.connected。\n    if (peerConnectionLooksHealthy(p2pPeer)) {\n        listenForMessages(currentFriendPk);\n        transitionToState(STATE_CONNECTED);\n        return;\n    }\n\n    transitionToState(STATE_CONNECTING);\n    listenForMessages(currentFriendPk);\n    scheduleReconnect('foreground-resume', true);\n}\n\ndocument.addEventListener('visibilitychange', function() {\n    if (document.hidden) {\n        appHiddenAt = Date.now();\n        return;\n    }\n\n    if (!navigator.onLine) return;\n    if (foregroundRecoveryTimer) clearTimeout(foregroundRecoveryTimer);\n    foregroundRecoveryTimer = setTimeout(function() {\n        foregroundRecoveryTimer = null;\n        recoverAfterForeground();\n    }, 120);\n});\n\n// iOS 有時 pageshow / focus 先於或取代 visibilitychange。\nwindow.addEventListener('pageshow', function() {\n    if (!document.hidden && navigator.onLine) recoverAfterForeground();\n});\nwindow.addEventListener('focus', function() {\n    if (!document.hidden && navigator.onLine) recoverAfterForeground();\n});'''
if old not in s:
    raise SystemExit('visibilitychange anchor not found')
s=s.replace(old,new,1)
p.write_text(s)
