from pathlib import Path
p=Path('index.html')
s=p.read_text()

s=s.replace('html, body { width: 100%; height: 100%; margin: 0; overflow: hidden; background: var(--bg); overscroll-behavior: none; }\n        html { position: fixed; inset: 0; }\n        body { position: fixed; inset: 0; width: 100%; height: 100%; }',
'''html, body { width: 100%; height: 100%; margin: 0; overflow: hidden; background: var(--bg); overscroll-behavior: none; }''',1)

s=s.replace('            height: 100dvh;\n            min-height: 100dvh;', '            height: var(--vv-height, 100dvh);\n            min-height: 0;',1)
s=s.replace('            position: fixed;', '            position: absolute;',1)
s=s.replace('            top: 0;\n            left: 0;\n            right: 0;\n            transform: none;', '            top: 0;\n            left: 0;\n            right: 0;\n            transform: translate3d(0, var(--vv-top, 0px), 0);\n            will-change: transform, height;',1)
s=s.replace('        #chat-input-area {\n            flex: 0 0 auto;\n            position: sticky;\n            bottom: 0;\n            z-index: 5;', '        #chat-input-area {\n            flex: 0 0 auto;\n            position: relative;\n            z-index: 5;',1)

marker='''    <script type="module">\n        const versionStamp = "20260815-v25-native-keyboard";'''
script='''    <script>\n        (function() {\n            const root = document.documentElement;\n            const chat = document.getElementById('chat-interface');\n            const input = document.getElementById('input-msg');\n            const messages = document.getElementById('chat-messages');\n            let raf = 0;\n\n            function applyVisualViewport() {\n                raf = 0;\n                const vv = window.visualViewport;\n                const height = Math.round(vv ? vv.height : window.innerHeight);\n                const top = Math.max(0, Math.round(vv ? vv.offsetTop : 0));\n\n                const bottomGap = messages\n                    ? Math.max(0, messages.scrollHeight - messages.scrollTop - messages.clientHeight)\n                    : 0;\n                const keepAtBottom = document.activeElement === input && bottomGap < 96;\n\n                root.style.setProperty('--vv-height', `${height}px`);\n                root.style.setProperty('--vv-top', `${top}px`);\n\n                if (keepAtBottom && messages) {\n                    requestAnimationFrame(function() {\n                        messages.scrollTop = Math.max(0, messages.scrollHeight - messages.clientHeight - bottomGap);\n                    });\n                }\n            }\n\n            function scheduleVisualViewport() {\n                if (raf) return;\n                raf = requestAnimationFrame(applyVisualViewport);\n            }\n\n            scheduleVisualViewport();\n            window.addEventListener('resize', scheduleVisualViewport, { passive: true });\n            window.addEventListener('orientationchange', scheduleVisualViewport, { passive: true });\n\n            if (window.visualViewport) {\n                window.visualViewport.addEventListener('resize', scheduleVisualViewport, { passive: true });\n                window.visualViewport.addEventListener('scroll', scheduleVisualViewport, { passive: true });\n            }\n\n            input.addEventListener('focus', scheduleVisualViewport);\n            input.addEventListener('blur', scheduleVisualViewport);\n        })();\n    </script>\n\n    <script type="module">\n        const versionStamp = "20260815-v26-visual-viewport-shell";'''
if marker not in s:
    raise SystemExit('version marker not found')
s=s.replace(marker,script,1)
p.write_text(s)
